// All hub content lives here. To add a project, copy an entry and edit it.
//   category: "AI" | "Data" | ".NET" | "Full-stack" | "Desktop" | "Games"
//   featured: true highlights the card and puts it first
//   live: optional link to a running demo
//   image: optional screenshot shown on a featured card, e.g. "screenshots/claimlens.png" (16:9 works best);
//          without it the card has no thumbnail

window.PROFILE = {
  name: "Troy Clarke",
  tagline: "Web | Data | Cloud",
  headline: "I build fast, reliable apps — from idea to production.",
  intro:
    "Senior Full-stack developer working across .NET, Python and TypeScript, with a growing focus on data platforms and AI-assisted products. Below are my recent projects, newest first.",
  links: {
    GitHub: "https://github.com/troyclarke69",
    LinkedIn: "https://www.linkedin.com/in/troy-clarke-6752ba9/",
    Email: "mailto:teclarke@rogers.com",
    Résumé: "Troy_Clarke_Resume.pdf",
  },
};

window.PROJECTS = [
  {
    repo: "freight-audit",
    title: "Freight Invoice Audit Agent",
    category: "AI",
    year: 2026,
    featured: true,
    live: "https://troyclarke69.github.io/freight-audit/",
    summary: "Multi-tenant agent that audits freight invoices against contracts and bills of lading, with a per-tenant autonomy gate deciding what it can action on its own.",
    tech: ["TypeScript", "React", "Vite", "Zod", "Claude"],
  },
  {
    repo: "claimLens",
    title: "ClaimLens",
    category: "AI",
    year: 2026,
    featured: true,
    live: "https://troyclarke69.github.io/claimLens/",
    summary: "Evidence-cited extraction from scanned insurance claims: a vision-language model fine-tuned with SFT and GRPO, with fairness evals and a hash-chained audit trail.",
    tech: ["TypeScript", "Python", "Angular", "FastAPI", "Pydantic", "Pandas", "NumPy", "PyTorch", "Transformers", "PEFT"],
  },
  {
    repo: "abrain",
    title: "aBrain",
    category: "Full-stack",
    year: 2026,
    featured: true,
    summary: "Job search and analytics platform with a résumé matcher and optimizer.",
    tech: ["TypeScript", "Python", "React", "Next.js", "Tailwind", "FastAPI", "Pydantic", "SQLAlchemy", "Postgres", "dbt", "Pandas", "NextAuth", "JWT", "bcrypt", "Recharts"],
  },
  {
    repo: "vibe",
    title: "Vibe",
    category: "AI",
    year: 2026,
    featured: true,
    summary: "Type a high-level “vibe”, get back a structured task list. Clean Architecture backend, a dedicated AI agent, and two real databases.",
    tech: ["TypeScript", "Python", "React", "Next.js", "Tailwind", "FastAPI", "Express", "Pydantic", "Postgres", "MongoDB", "Claude", "OpenAI"],
  },
  {
    repo: "smed",
    title: "SMED",
    category: ".NET",
    year: 2026,
    featured: true,
    summary: "Financial-services app: relational database engineering, a secure layered Web API, React and Blazor clients, vulnerability scanning and CI/CD.",
    tech: ["TypeScript", "C#", "React", "Vite", "Blazor", "Swagger", "FluentValidation", "Entity Framework", "Dapper", "SQL Server", "JWT", "bcrypt"],
  },
  {
    repo: "rbac",
    title: "RBAC Identity Service",
    category: ".NET",
    year: 2026,
    featured: true,
    summary: "Standalone identity service with users, roles and permissions, RS256 JWTs, permission-based middleware and PBKDF2 hashing.",
    tech: ["C#", "Dapper", "SQL Server", "JWT"],
  },
  {
    repo: "mini-faire",
    title: "Mini Faire",
    category: "Data",
    year: 2026,
    featured: true,
    summary: "Retail marketplace analytics platform: data contracts, batch + event ingestion, quarantine, a DuckDB warehouse, semantic metrics and an API.",
    tech: ["TypeScript", "Python", "React", "Next.js", "Tailwind", "FastAPI", "Pydantic", "WebSockets", "DuckDB", "Polars"],
  },
  {
    repo: "mini-paypal",
    title: "MiniPayPal",
    category: ".NET",
    year: 2026,
    summary: "Wallet and payments backend with atomic, idempotent transfers on an immutable double-entry ledger.",
    tech: ["TypeScript", "C#", "React", "React Router", "Vite", "Swagger", "Entity Framework", "Postgres", "JWT", "bcrypt"],
  },
  {
    repo: "mini_attribution_engine",
    title: "Marketing Attribution Engine",
    category: "Data",
    year: 2026,
    summary: "Ingests ads, clickstream and orders into BigQuery, applies 7-day last-touch attribution, and serves a campaign dashboard.",
    tech: ["JavaScript", "Python", "React", "Vite", "FastAPI", "Pydantic", "BigQuery", "Airflow", "Pandas", "NumPy", "scikit-learn", "Recharts"],
  },
  {
    repo: "triune",
    title: "Triune",
    category: "AI",
    year: 2026,
    summary: "A “self-evolving digital organism” merged from three AI-authored prototypes into one event-driven mesh with an adaptive UI.",
    tech: ["TypeScript", "React", "Vite", "Express", "Temporal", "NATS", "WebSockets", "Postgres", "Redis"],
  },
  {
    repo: "ProjectSeven",
    title: "Project Seven",
    category: "AI",
    year: 2026,
    summary: "Multi-tenant project registry that writes and refreshes project documentation with Claude (Gemini as a fallback), triggered by GitHub webhooks, with doc history snapshots.",
    tech: ["TypeScript", "React", "Next.js", "Drizzle", "Postgres", "Firebase", "Claude", "Gemini", "NextAuth", "bcrypt"],
  },
  {
    repo: "blackjackmatch-game",
    title: "Blackjack Match",
    category: "Games",
    year: 2026,
    summary: "A Blackjack + Match combo game written in plain JavaScript in 2021, reimagined with AI in 2026 — now with an Android version.",
    tech: ["JavaScript", "Capacitor", "Android"],
  },
  {
    repo: "SeeYou2",
    title: "SeeYou2",
    category: "Desktop",
    year: 2026,
    summary: "Windows desktop scanner that checks running processes, startup entries, browser extensions and the UI Automation tree for software quietly watching the system, with a risk score and plain-language advice.",
    tech: ["TypeScript", "Rust", "React", "React Router", "Tailwind", "Vite", "Tauri"],
  },
  {
    repo: "tcrm",
    title: "TCRM",
    category: "Full-stack",
    year: 2026,
    summary: "CRM demo with a .NET API, Postgres and a React + Tailwind front end.",
    tech: ["TypeScript", "C#", "React", "React Router", "Tailwind", "Vite", "Swagger", "Entity Framework", "Postgres", "JWT", "bcrypt"],
  },
  {
    repo: "TCHQ",
    title: "TCHQ Portfolio",
    category: "Full-stack",
    year: 2026,
    summary: "Portfolio app with a JWT-protected admin API for managing projects, and a contact form stored in Postgres.",
    tech: ["TypeScript", "Python", "React", "React Router", "Tailwind", "Vite", "FastAPI", "SQLAlchemy", "Postgres", "JWT", "bcrypt"],
  },
  {
    repo: "CherryTree",
    title: "Cherry Tree Co.",
    category: "Full-stack",
    year: 2026,
    summary: "Business site with a JWT-secured FastAPI backend, run with Docker Compose.",
    tech: ["TypeScript", "Python", "React", "Vite", "FastAPI", "Pydantic", "SQLAlchemy", "Postgres", "JWT", "bcrypt"],
  },
  {
    repo: "VTranslator",
    title: "VTranslator",
    category: "AI",
    year: 2026,
    summary: "Translation app that verifies each result by translating it back to the original language.",
    tech: ["Python", "Streamlit", "Gemini"],
  },
  {
    repo: "ngCorona-v1",
    title: "Corona Now",
    category: "Full-stack",
    year: 2020,
    live: "https://corona-now.netlify.app",
    summary: "COVID dashboard built on third-party APIs, with Google Charts.",
    tech: ["TypeScript", "Angular", "Angular Material", "Bootstrap", "Chart.js", "Google Charts"],
  },
];
