// All hub content lives here. To add a project, copy an entry and edit it.
//   category: "AI" | "Data" | ".NET" | "Full-stack" | "Games"
//   featured: true shows it in the top grid; archive: true moves it to the "Earlier work" list
//   live: optional link to a running demo

window.PROFILE = {
  name: "Troy Clarke",
  tagline: "Web | Data | Cloud",
  headline: "I build fast, reliable apps — from idea to production.",
  intro:
    "Full-stack developer working across .NET, Python and TypeScript, with a growing focus on data platforms and AI-assisted products. Below is everything I've built, newest first.",
  links: {
    GitHub: "https://github.com/troyclarke69",
    LinkedIn: "https://www.linkedin.com/in/troy-clarke-6752ba9/",
    Email: "mailto:teclarke@rogers.com",
  },
};

window.PROJECTS = [
  {
    repo: "claimLens",
    title: "ClaimLens",
    category: "AI",
    year: 2026,
    featured: true,
    summary: "Evidence-cited extraction from insurance claim documents — a hands-on SFT + RL fine-tuning project.",
    tech: ["Python", "SFT", "RL", "LLMs"],
  },
  {
    repo: "abrain",
    title: "aBrain",
    category: "Full-stack",
    year: 2026,
    featured: true,
    summary: "Job search and analytics platform with a résumé matcher and optimizer.",
    tech: ["Next.js", "FastAPI", "Postgres", "dbt", "NextAuth"],
  },
  {
    repo: "vibe",
    title: "Vibe",
    category: "AI",
    year: 2026,
    featured: true,
    summary: "Type a high-level “vibe”, get back a structured task list. Clean Architecture backend, a dedicated AI agent, and two real databases.",
    tech: ["Next.js", "Node.js", "Python", "MongoDB", "Postgres"],
  },
  {
    repo: "smed",
    title: "SMED",
    category: ".NET",
    year: 2026,
    featured: true,
    summary: "Financial-services app: relational database engineering, a secure layered Web API, React and Blazor clients, vulnerability scanning and CI/CD.",
    tech: [".NET", "React", "Blazor", "SQL", "CI/CD"],
  },
  {
    repo: "rbac",
    title: "RBAC Identity Service",
    category: ".NET",
    year: 2026,
    featured: true,
    summary: "Standalone identity service with users, roles and permissions, RS256 JWTs, permission-based middleware and PBKDF2 hashing.",
    tech: [".NET", "Dapper", "JWT", "Security"],
  },
  {
    repo: "mini-faire",
    title: "Mini Faire",
    category: "Data",
    year: 2026,
    featured: true,
    summary: "Retail marketplace analytics platform: data contracts, batch + event ingestion, quarantine, a DuckDB warehouse, semantic metrics and an API.",
    tech: ["Python", "DuckDB", "Polars", "FastAPI"],
  },
  {
    repo: "mini-paypal",
    title: "MiniPayPal",
    category: ".NET",
    year: 2026,
    summary: "Wallet and payments backend with atomic, idempotent transfers on an immutable double-entry ledger.",
    tech: [".NET 8", "Postgres", "Clean Architecture"],
  },
  {
    repo: "mini_attribution_engine",
    title: "Marketing Attribution Engine",
    category: "Data",
    year: 2026,
    summary: "Ingests ads, clickstream and orders into BigQuery, applies 7-day last-touch attribution, and serves a campaign dashboard.",
    tech: ["Python", "BigQuery", "FastAPI", "React"],
  },
  {
    repo: "triune",
    title: "Triune",
    category: "AI",
    year: 2026,
    summary: "A “self-evolving digital organism” merged from three AI-authored prototypes into one event-driven mesh with an adaptive UI.",
    tech: ["TypeScript", "Event-driven", "Multi-agent"],
  },
  {
    repo: "ProjectSeven",
    title: "Project Seven",
    category: "AI",
    year: 2026,
    summary: "Project registry that auto-generates documentation from GitHub webhooks using Gemini.",
    tech: ["Next.js", "Firebase", "Gemini", "Webhooks"],
  },
  {
    repo: "blackjackmatch-game",
    title: "Blackjack Match",
    category: "Games",
    year: 2026,
    summary: "A Blackjack + Match combo game written in plain JavaScript in 2021, reimagined with AI in 2026 — now with an Android version.",
    tech: ["JavaScript", "Android"],
  },
  {
    repo: "SeeYou2",
    title: "SeeYou2",
    category: "AI",
    year: 2026,
    summary: "AI diagnostic tool.",
    tech: ["JavaScript", "AI"],
  },
  {
    repo: "tcrm",
    title: "TCRM",
    category: "Full-stack",
    year: 2026,
    summary: "CRM demo with a .NET API, Postgres and a React + Tailwind front end.",
    tech: [".NET", "Postgres", "React", "Tailwind"],
  },
  {
    repo: "TCHQ",
    title: "TCHQ Portfolio",
    category: "Full-stack",
    year: 2026,
    summary: "Portfolio app with a JWT-protected admin API for managing projects, and a contact form stored in Postgres.",
    tech: ["React", "Tailwind", "FastAPI", "Postgres"],
  },
  {
    repo: "CherryTree",
    title: "Cherry Tree Co.",
    category: "Full-stack",
    year: 2026,
    summary: "Business site with a JWT-secured FastAPI backend, run with Docker Compose.",
    tech: ["React", "Vite", "FastAPI", "Postgres", "Docker"],
  },
  {
    repo: "VTranslator",
    title: "VTranslator",
    category: "AI",
    year: 2026,
    summary: "Translation app that verifies each result by translating it back to the original language.",
    tech: ["Python", "Streamlit", "Gemini"],
  },

  // Earlier work
  { repo: "ngCorona-v1", title: "Corona Now", category: "Full-stack", year: 2020, archive: true, live: "https://corona-now.netlify.app", summary: "COVID dashboard with third-party APIs and Google Charts.", tech: ["Angular"] },
  { repo: "nextjs_covid_test", title: "Next.js COVID", category: "Full-stack", year: 2022, archive: true, live: "https://nextjs-covid-test.vercel.app", summary: "COVID stats built with Next.js.", tech: ["Next.js"] },
  { repo: "CovidTracker", title: "CovidTracker", category: "Full-stack", year: 2021, archive: true, summary: "React app charting COVID data.", tech: ["React", "Chart.js"] },
  { repo: "next-realtor-test", title: "Real Estate App", category: "Full-stack", year: 2022, archive: true, summary: "Property listings app.", tech: ["Next.js"] },
  { repo: "ngOrder-v11", title: "ngOrder", category: "Full-stack", year: 2021, archive: true, summary: "Ordering app, upgraded from Angular 9 to 11.", tech: ["Angular", ".NET"] },
  { repo: "WikiVox-Api", title: "WikiVox API", category: ".NET", year: 2021, archive: true, summary: "Backend API for WikiVox and ngOrder.", tech: [".NET"] },
  { repo: "Wikivox", title: "WikiVox", category: ".NET", year: 2019, archive: true, summary: "ASP.NET Core MVC app.", tech: ["ASP.NET Core"] },
  { repo: "newsman", title: "Newsman", category: ".NET", year: 2020, archive: true, summary: "News app with Entity Framework.", tech: ["ASP.NET Core", "EF"] },
  { repo: "Googster", title: "Googster", category: ".NET", year: 2020, archive: true, summary: "ASP.NET Core MVC + EF playground.", tech: ["ASP.NET Core", "EF"] },
  { repo: "copd-api", title: "COPD API", category: ".NET", year: 2020, archive: true, summary: ".NET Core 3.1 MVC API.", tech: [".NET Core"] },
  { repo: "ng-Dash", title: "ng-Dash", category: "Full-stack", year: 2019, archive: true, summary: "Dashboard with Angular, Web API and PostgreSQL.", tech: ["Angular", "Web API", "Postgres"] },
  { repo: "tictactoe", title: "Tic-Tac-Toe", category: "Games", year: 2019, archive: true, summary: "My first React app.", tech: ["React"] },
];
